data:
        dataset_name: spcv2
        data_path: ~/dataset/speechcommand_v2

model:
         pretrained:
                 _target_: audiotrain.methods.clip.downstream.train_freeze_hydra.PretrainedAMamba2EncoderPLModule

                 ckpt_path: /models/model_path2/last.ckpt
                 chunk_len: 6  # second
                 n_blocks: 12
        linearclassfier:
                learning_rate:
                max_epochs:
                embed_dim:
                num_labels:
                nulti_label:
train:
        learning_rate: 
        batch_size:
        nproc:
        max_epochs:
        save_path:


        

