training:
  batch_size: [128, 128]
  median_window: 7
  n_test_thresholds: 50
  weak_split: 0.9
  batch_len_index: 1
  seed: 42
  val_thresholds: [0.5]
data:
  synth_train_num: 10000
  synth_folder: "/data/LCL/DESED2022/synth_train+val/SynthDataset/Train/soundscapes_16k/"
  synth_folder_44k: "/data/LCL/DESED2022/synth_train+val/SynthDataset/Train/soundscapes_16k/"
  synth_tsv: "/data/LCL/DESED2022/annotations/synth_train(10000).tsv"
  weak_folder: "/data/LCL/DESED2022/weak_16k/weak_16k/"
  weak_folder_44k:  "/data/LCL/DESED2022/weak_16k/weak_16k/"
  weak_tsv: "/data/LCL/DESED2022/annotations/weak(1578).tsv"
  unlabeled_folder: "/data/LCL/DESED2022/unlabel_in_domain/unlabel_in_domain_16k/"
  unlabeled_folder_44k: "/data/LCL/DESED2022/unlabel_in_domain/unlabel_in_domain_16k/"
  synth_val_folder: "/data/LCL/DESED2022/synth_train+val/SynthDataset/Val/soundscapes_16k/"
  synth_val_folder_44k: "/data/LCL/DESED2022/synth_train+val/SynthDataset/Val/soundscapes_16k/"
  synth_val_tsv: "/data/LCL/DESED2022/annotations/synth_val(2500).tsv"
  synth_val_dur: "/data/LCL/DESED2022/annotations/synth_val_duration.tsv"
  test_folder: "/data/LCL/DESED2022/validation_16k/validation_16k/"
  test_folder_44k: "/data/LCL/DESED2022/validation_16k/validation_16k/"
  test_tsv: "/data/LCL/DESED2022/annotations/validation(1168).tsv"
  test_dur: "/data/LCL/DESED2022/annotations/validation_durations.tsv"
  eval_folder:  "/data/LCL/DESED2022/eval/eval23_16k/"
  eval_folder_44k:  "/data/LCL/DESED2022/eval/eval23_16k/"
  audio_max_len: 10
  fs: 16000
  net_subsample: 4
feats:
  n_mels: 128
  n_filters: 2048
  hop_length: 160
  n_window: 2048
  sample_rate: 16000
  f_min: 0
  f_max: 8000

